MyStore.Web/Models/DeliverViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyStore.Web.Models
{
    public class DeliverViewModel
    {
        public int Id { get; set; }



        [Required]
        [DisplayName("Delivery date")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd hh:mm tt}", ApplyFormatInEditMode = false)]
        public DateTime DeliveryDate { get; set; }
    }
}

MyStore.Web/Controllers/API/ProductsController.cs
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyStore.Web.Data.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyStore.Web.Controllers.API
{
    [Route("api/[controller]")]
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    [ApiController]
    public class ProductsController : Controller
    {
        private readonly IProductRepository _productRepository;
        public ProductsController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        [HttpGet]
        public IActionResult GetProducts()
        {
            return Ok(_productRepository.GetAllWithUsers());
        }
    }
}

MyStore.Web/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyStore.Web.Data.Repositories;
using MyStore.Web.Helpers;
using MyStore.Web.Models;

namespace ShopCET46.Web.Controllers
{
    
    public class OrdersController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly IProductRepository _productRepository;
        private readonly IMailHelper _mailHelper;

        public OrdersController(IOrderRepository orderRepository,
            IProductRepository productRepository,
            IMailHelper mailHelper)
        {
            _orderRepository = orderRepository;
            _productRepository = productRepository;
            _mailHelper = mailHelper;
        }


        public async Task<IActionResult> Index()
        {
            var model = await _orderRepository.GetOrdersAsync(this.User.Identity.Name);
            return View(model);
        }

        public IActionResult Checkout()
        {
            
            
            
            return View();
        }

        public async Task<IActionResult> Create()
        {
            var model = await _orderRepository.GetDetailTempsAsync(this.User.Identity.Name);
            if ((this.User.Identity.Name) == null)
            {
                return this.RedirectToAction("Login", "Account");
            }
            
            return View(model);
        }

        public async Task<IActionResult> Card(int id)
        {
            var model = await _orderRepository.GetByIdAsync(id);
            return View(model);
        }


        public IActionResult AddProduct()
        {
            var model = new AddItemViewModel
            {
                Quantity = 1,
                Products = _productRepository.GetComboProducts()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct(AddItemViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                await _orderRepository.AddItemToOrdemAsync(model, this.User.Identity.Name);
                return this.RedirectToAction("Create");
            }

            return this.View(model);
        }

        public async Task<IActionResult> DeleteItem(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await _orderRepository.DeleteDetailTempAsync(id.Value);
            return this.RedirectToAction("Create");
        }


        public async Task<IActionResult> DeleteOrder(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await _orderRepository.DeleteOrderAsync(id.Value);
            return this.RedirectToAction("Index");
        }

        public async Task<IActionResult> Increase(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await _orderRepository.ModifyDetailTempQuantityAsync(id.Value, 1);
            return this.RedirectToAction("Create");
        }

        public async Task<IActionResult> Decrease(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await _orderRepository.ModifyDetailTempQuantityAsync(id.Value, -1);
            return this.RedirectToAction("Create");
        }

        public async Task<IActionResult> ConfirmOrder()
        {
            var createdOrder = await _orderRepository.ConfirmOrderAsync(User.Identity.Name);

            if (createdOrder != null)
            {
                try
                {
                    EmailPDF generator = new EmailPDF();

                    var pdfByteArray = generator.PdfGenerate(createdOrder, User.Identity.Name);

                    _mailHelper.SendEmailPlusAttachment(User.Identity.Name, "Order - Plants Store",
                    "Thank you for choosing us.\n Please, check your email box! \n The purchase order follows attached", pdfByteArray);

                    ViewBag.Message = "Thank you for choosing us!\n\n\nPlease check your email box.";

                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }

            return RedirectToAction("Create");
        }

        [Authorize]
        public async Task<IActionResult> Deliver(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _orderRepository.GetOrderAsync(id.Value);
            if (order == null)
            {
                return NotFound();
            }

            var model = new DeliverViewModel
            {
                Id = order.Id,
                DeliveryDate = DateTime.Today
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Deliver(DeliverViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _orderRepository.DeliverOrderAsync(model);
                return this.RedirectToAction("Index");
            }
                        
            return View();
        }
    }
}

MyStore.Web/Views/Orders/AddProduct.cshtml
@model MyStore.Web.Models.AddItemViewModel

@{
    ViewData["Title"] = "AddProduct";
}
<section>
    <div style="margin:auto; width:1100px; height:300px">
        <br />
        <h2>Add Product</h2>
        <h4>To Order</h4>
        <br />
        <div class="row">
            <div class="col-md-5">
                <form asp-action="AddProduct">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="ProductId" class="control-label"></label>
                        <br />
                        <select asp-for="ProductId" asp-items="Model.Products" class="form-control"></select>
                        <span asp-validation-for="ProductId" class="text-danger"></span>
                        <br />
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="Quantity" class="control-label"></label>
                        <input asp-for="Quantity" class="form-control" type="number" />
                        <span asp-validation-for="Quantity" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                        <a asp-action="Index" class="btn btn-success">Back to List</a>
                    </div>
                </form>
                <br />
            </div>
            <br />
        </div>

    </div>
    <br />
    </section>
       

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }

MyStore.Web/Views/Orders/Create - Copy.cshtml
@model IEnumerable<MyStore.Web.Data.Entities.OrderDetailsTemp>

@{
    ViewData["Title"] = "Create";
}

    <section>
        <div style="margin:auto; width:1100px; height:300px">
            <br />
            <h2>New Order</h2>
            <br />
            <div class="row">
                <br />
                <div class="col-md-5">
                    <a asp-action="AddProduct" class="btn btn-success">Add Product</a>
                    <a asp-action="ConfirmOrder" class="btn btn-primary" id="btnConfirm">Confirm Order</a>



                </div>
                <br />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <br />
                <table class="table">
                    <br />
                    <br />
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Product.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Price)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Quantity)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Value)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Product.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Price)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Quantity)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Value)
                                </td>

                                <td id="@item.Id" align="right">
                                    <a asp-action="Increase" asp-route-id="@item.Id" class="genric-btn info small"><i class="fa fa-plus"></i></a>
                                    <a asp-action="Decrease" asp-route-id="@item.Id" class="genric-btn info small"><i class="fa fa-minus"></i></a>
                                    <a asp-action="DeleteItem" asp-route-id="@item.Id" class="genric-btn danger small" id="btnDeleteItem"><i class="fas fa-trash"></i></a>


                                    @*<a asp-action="DeleteItem" asp-route-id="@item.Id" class="btn btn-danger" id="btnDeleteItem">Delete</a>*@
                                </td>
                            </tr>
                            <hr />
                                }
                        </tbody>
                </table>

            </div>
            </div>
        </section>

                       
                        
                        <div id="deleteDialog" class="modal fade">
                            <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal"><i class="fa fa-window-close"></i></button>
                                        <h4 class="modal-title">Delete</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>Do you want to delete the product from order?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" id="btnYesDelete">Delete</button>
                                        <button type="button" class="btn btn-success" id="btnNoDelete">No</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        @section Scripts {

                            <script type="text/javascript">
                                $(document).ready(function () {
                                    var id = 0;
                                    /*Evento click em todos os <a> com o id = btnDeleteItem*/
                                    $('a[id*=btnDeleteItem]').click(function () {
                                        debugger;
                                        //console.log($(this).parent()[0]);
                                        id = $(this).parent()[0].id;
                                        $("#deleteDialog").modal('show');
                                        return false;
                                    });
                                    $("#btnNoDelete").click(function () {
                                        $("#deleteDialog").modal('hide');
                                        return false;
                                    });
                                    $("#btnYesDelete").click(function () {
                                        window.location.href = '/Products/DeleteItem/' + id;
                                    });
                                });
                            </script>
                        }

MyStore.Web/Views/Orders/Create.cshtml
@model IEnumerable<MyStore.Web.Data.Entities.OrderDetailsTemp>

    <main>
        <!--? slider Area Start-->
        <div class="slider-area ">
            <div class="slider-active">
                <div class="single-slider hero-overly2  slider-height2 d-flex align-items-center slider-bg2">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-6 col-lg-8 col-md-8">
                                <div class="hero__caption hero__caption2">
                                    <h1 data-animation="fadeInUp" data-delay=".4s">Cart List</h1>
                                    <nav aria-label="breadcrumb">
                                        <ol class="breadcrumb">
                                            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                                            <li class="breadcrumb-item"><a href="#">Cart List</a></li>
                                        </ol>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- slider Area End-->
        <!--================Cart Area =================-->
        <section class="cart_area section-padding40">
            <div class="container">
                <div class="cart_inner">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        Product
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Price)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Quantity)
                                    </th>
                                    <th>
                                        Total
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Product.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Price)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Quantity)
                                    </td>
                                    <td id="@item.Id" align="right">
                                        <a asp-action="Increase" asp-route-id="@item.Id" class="genric-btn primary small"><i class="ti-plus"></i></a>
                                        <a asp-action="Decrease" asp-route-id="@item.Id" class="genric-btn success small"><i class="ti-minus"></i></a>
                                        </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Value)
                                    </td>
                                    <td id="@item.Id" align="right">
                                        @*<a asp-action="Increase" asp-route-id="@item.Id" class="genric-btn primary small"><i class="ti-plus"></i></a>
                                        <a asp-action="Decrease" asp-route-id="@item.Id" class="genric-btn success small"><i class="ti-minus"></i></a>*@
                                        <a asp-action="DeleteItem" asp-route-id="@item.Id" class="genric-btn danger small" id="btnDeleteItem"><i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                                }
                            </tbody>
                    </table>
                        <div class="checkout_btn_inner float-right">
                            <a asp-controller="Products" asp-action="Shop" class="btn btn-success">Continue Shopping</a>
                            <a class="btn checkout_btn" asp-action="ConfirmOrder" class="btn btn-primary" id="btnConfirm">Proceed to checkout</a>
                        </div>
                </div>
            </div>
            </div>
        </section>
        <!--================End Cart Area =================-->
    </main>

          


            <div id="deleteDialog" class="modal fade">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><i class="fa fa-window-close"></i></button>
                            <h4 class="modal-title">Delete</h4>
                        </div>
                        <div class="modal-body">
                            <p>Do you want to delete the product from order?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" id="btnYesDelete">Delete</button>
                            <button type="button" class="btn btn-success" id="btnNoDelete">No</button>
                        </div>
                    </div>
                </div>
            </div>

            @section Scripts {

                <script type="text/javascript">
                    $(document).ready(function () {
                        var id = 0;
                        /*Evento click em todos os <a> com o id = btnDeleteItem*/
                        $('a[id*=btnDeleteItem]').click(function () {
                            debugger;
                            //console.log($(this).parent()[0]);
                            id = $(this).parent()[0].id;
                            $("#deleteDialog").modal('show');
                            return false;
                        });
                        $("#btnNoDelete").click(function () {
                            $("#deleteDialog").modal('hide');
                            return false;
                        });
                        $("#btnYesDelete").click(function () {
                            window.location.href = '/Products/DeleteItem/' + id;
                        });
                    });
                </script>
            }

MyStore.Web/Views/Orders/Deliver.cshtml
@model MyStore.Web.Models.DeliverViewModel

@{
    ViewData["Title"] = "Deliver";
}

<h2>Deliver</h2>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Deliver">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="DeliveryDate" class="control-label"></label>
                <input asp-for="DeliveryDate" class="form-control" />
                <span asp-validation-for="DeliveryDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-success">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyStore.Web/Views/Orders/Index.cshtml
@model IEnumerable<MyStore.Web.Data.Entities.Order>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
<section>
    <div style="margin:auto; width:95%;">
        <br />
        <br />
        <br />
        <p>
            <a asp-controller="Orders" asp-action="Create" class="btn btn-primary"><i class="fa fa-plus"></i> Orders</a>
        </p>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Orders</h3>
                        <br />
                    </div>
                    <div class="panel-boby">
                        <table class="table" table-hover table-responsive table-striped" id="MyTable">
                            <thead>
                                <tr>
                                    @if (this.User.IsInRole("Admin"))
                                    {
                                        <th>
                                            @Html.DisplayNameFor(model => model.User.Name)
                                        </th>
                                    }
                                    <th>
                                        @Html.DisplayNameFor(model => model.OrderDateLocal)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.DeliveryDate)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Lines)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Quantity)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Value)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        @if (this.User.IsInRole("Admin"))
                                        {
                                            <th>
                                                @Html.DisplayFor(modelItem => item.User.Name)
                                            </th>
                                        }
                                        <td>
                                            @Html.DisplayFor(modelItem => item.OrderDateLocal)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.DeliveryDate)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Lines)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Quantity)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Value)
                                        </td>
                                        <td id="@item.Id" align="right">
                                            <a asp-action="Deliver" asp-route-id="@item.Id" class="genric-btn primary large" id="btnDeliver"><i class="fas fa-truck"></i></a>
                                            <a asp-action="Delete" asp-route-id="@item.Id" class="genric-btn danger large" id="btnDelete"><i class="fas fa-trash"></i></a>
                                        </td>



                                        @*<td>
                                                <a asp-action="Deliver" asp-route-id="@item.Id" class="btn btn-info" id="btnDeliver">Deliver</a>
                                                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger" id="btnDelete">Delete</a>
                                            </td>*@
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
    <br />
    <br />
</section>

@*@section Scripts{
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#MyTable').DataTable();
        });

    </script>
}*@



<div id="deleteDialog" class="modal fade">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><i class="fa fa-window-close"></i></button>
                <h4 class="modal-title">Delete</h4>
            </div>
            <div class="modal-body">
                <p>Do you want to delete the order?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" id="btnYesDelete">Delete</button>
                <button type="button" class="btn btn-success" id="btnNoDelete">No</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {

    <script type="text/javascript">
        $(document).ready(function () {
            var id = 0;

            /*Evento click em todos os <a> com o id = btnDeleteItem*/
            $('a[id*=btnDelete]').click(function () {
                debugger;
                //console.log($(this).parent()[0]);
                id = $(this).parent()[0].id;
                $("#deleteDialog").modal('show');
                return false;
            });
            $("#btnNoDelete").click(function () {
                $("#deleteDialog").modal('hide');
                return false;
            });
            $("#btnYesDelete").click(function () {
                window.location.href = '/Orders/DeleteOrder/' + id;
            });
        });
    </script>
}

MyStore.Web/Views/Orders/OrderNotFound.cshtml
@{
    ViewData["Title"] = "Order Not Found";
}

<h2>ORDER NOT FOUND</h2>